services:
  - type: web
    name: smart-billing-app
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn app:app --chdir backend"
    plan: free
    autoDeploy: true

