services:
  - type: web
    name: smart-billing-app
    env: python
    buildCommand: "pip install -r backend/requirements.txt"  
    startCommand: "gunicorn backend.app:app"  
    plan: free
    autoDeploy: true
